version: "3.9"

services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    user: "${UID}:${GID}"
    volumes:
      - ./:/var/www
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: BRIDAL_DB
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: bridal_user
      MYSQL_PASSWORD: bridal_pass
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel
networks:
  laravel:
volumes:
  dbdata: